### ISSUE TITLE
I have set up Postgres and Lighthouse and both are running. However, I am facing an issue when trying to run chaind

### ISSUE THREAD

**Issue by nukeTK** [wealdtech/chaind#109]
Steps to Reproduce
Set Up Geth and Lighthouse

I am running two services in different terminals:

1st Terminal (Geth):

```
geth --http --http.api eth,net,engine,admin --authrpc.jwtsecret ~/secrets/jwt.hex --authrpc.port 8551
```
2nd Terminal (Lighthouse Beacon Node):

```
lighthouse bn \
  --network mainnet \
  --execution-endpoint http://localhost:8551 \
  --execution-jwt ~/secrets/jwt.hex \
  --checkpoint-sync-url https://sync-mainnet.beaconcha.in \
  --disable-deposit-contract-sync
```

Set Up PostgreSQL

I installed PostgreSQL through Homebrew and started it with the following commands:

```
brew install postgresql
brew services start PostgreSQL
```

Configure chaind

I configured the chaind YAML file located at ~/.chaind.yml as follows:

```
# Base log level of the process
log-level: info

# Log output file
log-file: /var/log/chaind.log

chaindb:
  # URL of the PostgreSQL database
  url: postgres://chain:secret@localhost:5432/chain
  max-connections: 16

eth2client:
  # Log level of the Ethereum 2 client module
  log-level: debug
  # Address of the beacon node
  address: localhost:5052

eth1client:
  # Address of the Ethereum 1 node
  address: localhost:8551

blocks:
  enable: true
  address: localhost:5052

validators:
  enable: true
  balances:
    enable: false

beacon-committees:
  enable: true

proposer-duties:
  enable: true

finalizer:
  enable: true

eth1deposits:
  enable: false

summarizer:
  enable: true
  epochs:
    enable: true
  blocks:
    enable: true
  validators:
    enable: false
```

Run chaind

When I try to run chaind with the following command, it runs but does nothing:

```
sudo chaind --chaindb.url=postgres://chain:secret@localhost:5432/chain --eth2client.address=http://localhost:5052
```

The command runs but does not produce any output or fetch the required data.

Request for Assistance: Need to fetch
(I need to fetch data on the withdrawal slot and epoch data of validator index that is shown on the UI of Beacon Chain)
Please provide the correct command to fetch the data and any troubleshooting steps or configuration changes that might be needed.
