### ISSUE TITLE
Many blocks are marked as non-canonical on Ropsten

### ISSUE THREAD

**Issue by remyroy** [wealdtech/chaind#47]
I used chaind with Geth (1.10.19-stable) and Lighthouse (v2.3.1-564d7da) on Ropsten and it seems like chaind found some non-canonical blocks that should be.

One of these blocks is [101174](https://ropsten.beaconcha.in/block/101174). That block is marked as non-canonical which seems incorrect.

```sql
SELECT * FROM t_blocks WHERE f_slot = 101174;
```

```csv
f_slot,f_proposer_index,f_root,f_graffiti,f_randao_reveal,f_body_root,f_parent_root,f_state_root,f_canonical,f_eth1_block_hash,f_eth1_deposit_count,f_eth1_deposit_root
101174,100373,\xdb99244fbc9cc7d0c609a31db3f447ae6fc92742a38ca2f253ba88ee7f25b3b0,\x4574685374616b65720000000000000000000000000000000000000000000000,\xaf8c804a965b66b43d8b2ad1a99b7b14dfcca11c5899719c10906ad6efa51d0efc5e3248d660425872adbce0767622f0164248e828ebdd568e1b65a7a6602f4276cac073c50e044428ae32c94aab3d40d0f9aba8d007c556842e1faf60071c7c,\x16e999dcbeef20c778525d8af6f54561c3c0488d0ebbed922ebda8e6ee995267,\x8748c779e4dd88beffe6377636ba742da94c6ea49e55bf499e606aa2952a5950,\x5f89f824ad7e86d50f76deeef8c63f120aaf3273b23ea1a17c8d5f1555c448bf,f,\x14821ab7f67a8b395322b04e49e83bbbe2b913919c1852d96b6e92d7a29566ec,1553,\x60834f12b9b226a0d73fb55863941c44147cff6ef23fd63bb8866fbfab5f672a
```

Here are the logs I got while running chaind.

```
{"level":"info","version":"0.6.10","time":"2022-06-23T03:31:37Z","message":"Starting chaind"}
{"level":"info","service":"synccommittees","impl":"standard","period":0,"time":"2022-06-23T03:31:37Z","message":"Catching up from period"}
{"level":"info","service":"synccommittees","impl":"standard","time":"2022-06-23T03:31:38Z","message":"Caught up"}
{"level":"info","service":"blocks","impl":"standard","slot":0,"time":"2022-06-23T03:31:38Z","message":"Catching up from slot"}
{"level":"info","service":"validators","impl":"standard","epoch":0,"time":"2022-06-23T03:31:38Z","message":"Catching up from epoch"}
{"level":"info","time":"2022-06-23T03:31:38Z","message":"All services operational"}
{"level":"info","service":"eth1deposits","impl":"getlogs","block":0,"time":"2022-06-23T03:31:38Z","message":"Last processed block"}
{"level":"info","service":"proposerduties","impl":"standard","epoch":0,"time":"2022-06-23T03:31:38Z","message":"Catching up from epoch"}
{"level":"info","service":"beaconcommittees","impl":"standard","epoch":0,"time":"2022-06-23T03:31:38Z","message":"Catching up from epoch"}
{"level":"info","service":"validators","impl":"standard","epoch":5292,"time":"2022-06-23T03:31:53Z","message":"Caught up"}
{"level":"info","service":"eth1deposits","impl":"getlogs","time":"2022-06-23T03:42:07Z","message":"Caught up"}
{"level":"info","service":"proposerduties","impl":"standard","time":"2022-06-23T03:50:38Z","message":"Caught up"}
{"level":"info","service":"beaconcommittees","impl":"standard","time":"2022-06-23T04:05:23Z","message":"Caught up"}
{"level":"error","service":"finalizer","impl":"standard","epoch":5291,"error":"Failed to update canonical blocks on finality: failed to update canonical blocks from canonical root: failed to store block: failed to set block: ERROR: duplicate key value violates unique constraint \"i_blocks_1\" (SQLSTATE 23505)","time":"2022-06-23T04:08:42Z","message":"Failed to run finality transaction"}
{"level":"error","service":"finalizer","impl":"standard","epoch":5292,"error":"Failed to update canonical blocks on finality: failed to update canonical blocks from canonical root: failed to store block: failed to set block: ERROR: duplicate key value violates unique constraint \"i_blocks_1\" (SQLSTATE 23505)","time":"2022-06-23T04:41:58Z","message":"Failed to run finality transaction"}
{"level":"info","service":"blocks","impl":"standard","time":"2022-06-23T05:02:51Z","message":"Caught up"}
{"level":"warn","service":"blocks","impl":"standard","error":"no rows in result set","slot":172032,"sync_committee_period":21,"time":"2022-06-23T12:26:27Z","message":"Failed to obtain sync committee period"}
{"level":"warn","service":"blocks","impl":"standard","slot":172032,"error":"failed to update sync aggregate: failed to obtain database sync aggregate: failed to obtain sync committee: no rows in result set","time":"2022-06-23T12:26:27Z","message":"Failed to update block"}
```

[Here is the full dump of my PostgreSQL database using custom format](https://drive.google.com/file/d/1Tt7xLtQAWpFWnSR5AUgvwQFP4hqRn3tN/view?usp=sharing).

**Comment by remyroy** [comment]
Here is my yml configuration:

```yml
# log-level is the base log level of the process.
# 'info' should be a suitable log level, unless detailed information is
# required in which case 'debug' or 'trace' can be used.
log-level: info
# log-file specifies that log output should go to a file.  If this is not
# present log output will be to stderr.
#log-file: /var/log/chaind.log
chaindb:
  # url is the URL of the PostgreSQL database.
  url: postgres://chain:chain@localhost:5432
# eth2client contains configuration for the Ethereum 2 client.
eth2client:
  # log-level is the log level of the specific module.  If not present the base log
  # level will be used.
  log-level: debug
  # address is the address of the beacon node.
  address: localhost:5052
# eth1client contains configuration for the Ethereum 1 client.
eth1client:
  # address is the address of the Ethereum 1 node.
  address: localhost:8545
# blocks contains configuration for obtaining block-related information.
blocks:
  # enable states if this module will be operational.
  enable: true
  # address is a separate connection for this module.  If not present then
  # chaind will use the eth2client connection.
  #address: localhost:5051
  # start-slot is the slot from which to start.  chaind should keep track of this itself,
  # however if you wish to start from a later slot this can be set.
  # start-slot: 2000
  # refetch will refetch block data from a beacon node even if it has already has a block
  # in its database.
  # refetch: false
# validators contains configuration for obtaining validator-related information.
validators:
  enable: true
  # balances contains configuration for obtaining validator balances.  This is
  # a separate configuration flag for two reasons.  First, it can take a long
  # time to retrieve this information.  Second, the information can be
  # derived from the data obtained by the other modules.
  balances:
    enable: false
# beacon-committees contains configuration for obtaining beacon committee-related
# information.
beacon-committees:
  enable: true
# proposer-duties contains configuration for obtaining proposer duty-related
# information.
proposer-duties:
  enable: true
# finalizer updates tables with information available for finalized states.
finalizer:
  enable: true
# eth1deposits contains information about transacations made to the deposit contract
# on the Ethereum 1 network.
eth1deposits:
  enable: true
  # start-block is the block from which to start fetching deposits.  chaind should
  # keep track of this itself, however if you wish to start from a different block this
  # can be set.
  # start-block: 500
```
