### ISSUE TITLE
blocks.start-slot getting overwritten by requiresRefetch the first time chaind is started

### ISSUE THREAD

**Issue by samlaf** [wealdtech/chaind#80]
This is my config
```
############## BALANCE TABLE SIZE ##################
summarizer:
  validators:
    balance-retention: "P1D"

############## TABLES ##################
# blocks contains configuration for obtaining block-related information.
blocks:
  # enable states if this module will be operational.
  enable: true
  # start-slot is the slot from which to start.  chaind should keep track of this itself,
  # however if you wish to start from a later slot this can be set.
  start-slot: 43200 # this is the shapella fork slot number
# validators contains configuration for obtaining validator-related information.
validators:
  enable: true
  # balances contains configuration for obtaining validator balances.  This is
  # a separate configuration flag for two reasons.  First, it can take a long
  # time to retrieve this information.  Second, the information can be
  # derived from the data obtained by the other modules.
  balances:
    enable: true
# beacon-committees contains configuration for obtaining beacon committee-related
# information.
beacon-committees:
  enable: false
# proposer-duties contains configuration for obtaining proposer duty-related
# information.
proposer-duties:
  enable: false
# finalizer updates tables with information available for finalized states.
finalizer:
  enable: false
sync-committee:
  enable: false
# eth1deposits contains information about transactions made to the deposit contract
# on the Ethereum 1 network.
eth1deposits:
  enable: false
  # start-block is the block from which to start fetching deposits.  chaind should
  # keep track of this itself, however if you wish to start from a different block this
  # can be set.
  # start-block: 500
```

Basically just trying to get withdrawal credentials, and latest balance of validators. We don't need deposits so I was thinking we only need to fetch blocks and sync from the shapella fork, which on zhejiang is slot 43200.

When I nuke the db and start chaind, it still fetches all blocks:
```
{"level":"info","version":"0.7.0-rc1","time":"2023-02-10T21:44:43Z","message":"Starting chaind"}
{"level":"debug","time":"2023-02-10T21:44:43Z","message":"No tracing endpoint supplied; tracing not enabled"}
{"level":"debug","time":"2023-02-10T21:44:43Z","message":"No metrics service supplied; monitor not starting"}
{"level":"debug","time":"2023-02-10T21:44:43Z","message":"no metrics will be generated for this module"}
{"level":"info","service":"synccommittees","impl":"standard","period":-1,"time":"2023-02-10T21:44:43Z","message":"Catching up from period"}
{"level":"info","service":"synccommittees","impl":"standard","time":"2023-02-10T21:44:44Z","message":"Caught up"}
{"level":"info","service":"blocks","impl":"standard","slot":18446744073709551615,"time":"2023-02-10T21:44:44Z","message":"Catching up from slot"}
{"level":"info","time":"2023-02-10T21:44:44Z","message":"All services operational"}
{"level":"info","service":"validators","impl":"standard","epoch":0,"time":"2023-02-10T21:44:44Z","message":"Catching up from epoch"}
{"level":"debug","service":"blocks","impl":"standard","slot":0,"time":"2023-02-10T21:44:44Z","message":"Obtained beacon committees from API"}
{"level":"debug","service":"blocks","impl":"standard","slot":2,"time":"2023-02-10T21:44:44Z","message":"No beacon block obtained for slot"}
```
I stop chaind and restart it (while keeping the db), and only then it starts syncing from slot 43200.
```
{"level":"info","version":"0.7.0-rc1","time":"2023-02-10T21:45:37Z","message":"Starting chaind"}
{"level":"debug","time":"2023-02-10T21:45:37Z","message":"No tracing endpoint supplied; tracing not enabled"}
{"level":"debug","time":"2023-02-10T21:45:37Z","message":"No metrics service supplied; monitor not starting"}
{"level":"debug","time":"2023-02-10T21:45:37Z","message":"no metrics will be generated for this module"}
{"level":"info","service":"synccommittees","impl":"standard","period":8,"time":"2023-02-10T21:45:37Z","message":"Catching up from period"}
{"level":"info","service":"synccommittees","impl":"standard","time":"2023-02-10T21:45:37Z","message":"Caught up"}
{"level":"info","service":"blocks","impl":"standard","slot":43199,"time":"2023-02-10T21:45:37Z","message":"Catching up from slot"}
{"level":"info","time":"2023-02-10T21:45:37Z","message":"All services operational"}
{"level":"info","service":"validators","impl":"standard","epoch":0,"time":"2023-02-10T21:45:37Z","message":"Catching up from epoch"}
{"level":"debug","service":"blocks","impl":"standard","slot":43199,"time":"2023-02-10T21:45:37Z","message":"Obtained beacon committees from API"}
{"level":"debug","service":"blocks","impl":"standard","slot":43200,"time":"2023-02-10T21:45:37Z","message":"Obtained beacon committees from API"}
```

This is because [this line](https://github.com/wealdtech/chaind/blob/72d6eb1480827f33a3b5b8936e31c2a0190c2245/main.go#L287) is run the first time but not the second. When we need to refetch (whether first time running chaind, or setting the flag explicitly), shouldn't we only start syncing from `blocks.start-slot`? Is there a reason why not? Seems like a bug but I'm not 100% sure.
