### ISSUE TITLE
Chaind downloading old blocks (ignoring blocks.start-slot parameter)

### ISSUE THREAD

**Issue by got3nks** [wealdtech/chaind#81]
My goal is to run **chaind** with only recent data (i.e. last 24/48 hours).

I started **chaind** sync with `blocks.start-slot: 5790000`. At first it worked, downloading only blocks after the specified slot.

I then removed `blocks.start-slot` from the configuration (as suggested, to avoid forced re-scans at future restart of the process), few moments later `t_blocks` table catched up with the chain tip.

`{"level":"info","service":"blocks","impl":"standard","time":"2023-02-13T21:35:32+01:00","message":"Caught up"}`

But now it is downloading old blocks data (and full history from slot 0 of `t_beacon_committees` which is still catching up with the chain tip, and `t_proposer_duties` which didn't take a very long time).

```
SELECT * FROM t_metadata 
"schema"	"{""version"": 11}"
"synccommittees.standard"	"{""latest_period"": 707}"
"proposerduties.standard"	"{""latest_epoch"": 181177}"
"finalizer.standard"	"{""latest_epoch"": 75471, ""latest_canonical_slot"": 2415072}"
"beaconcommittees.standard"	"{""latest_epoch"": 162866}"
"validators.standard"	"{""latest_epoch"": 181177, ""latest_balances_epoch"": 0}"
"blocks.standard"	"{""latest_slot"": 5797407}"

SELECT count(f_slot) FROM t_blocks WHERE f_slot < 5790000
2388518
```

Current configuration file chaind.yml:
```
log-level: debug
log-file: /home/chaind/chaind.log
chaindb:
  url: postgres://chain:xxx@localhost:5432
  max-connections: 16
eth2client:
  log-level: debug
  address: localhost:5052
eth1client:
  address: localhost:8545
blocks:
  enable: true
  address: localhost:5052
  # start-slot: 5790000
validators:
  enable: true
  balances:
    enable: false
beacon-committees:
  enable: true
proposer-duties:
  enable: true
finalizer:
  enable: true
eth1deposits:
  enable: false
summarizer:
  enable: false
```
